name: Build Python Wheel

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install make
        python -m pip install --upgrade pip
        python -m pip install wheel venv

    - name: Create Virtualenv and Build Wheel
      run: |
        python -m venv .venv
        make venv
        make bdist_wheel
