name: Build Python Wheel

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel

    - name: Create Virtualenv and Build Wheel
      run: |
        python -m venv .venv
        make venv
        make bdist_wheel

    - name: Upload Wheel as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-wheel
        path: dist/*.whl

