name: Build Python Wheel

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel

    - name: Create Virtualenv and Build Wheel
      run: |
        python -m venv venv
        source venv/bin/activate
        python setup.py venv
        python setup.py bdist_wheel
